name: 'Setup PHP Action'
author: shivammathur
description: 'Setup PHP with required extensions, php.ini configuration, code-coverage support and various tools like composer'
branding:
  color: 'purple'
  icon: 'play-circle'
inputs:
  php-version:
    description: 'Setup PHP version.'
    default: '7.4'
    required: true
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage: 
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
