name: 'Setup PHP Action'
author: shivammathur
description: 'GitHub action to setup PHP with required extensions, php.ini configuration, code-coverage support and composer'
branding:
  color: 'purple'
inputs:
  php-version:
    description: 'Setup PHP version.'
    default: '7.4'
    required: true
  extensions:
    description: 'Setup PHP extensions.'
    required: false
  ini-values:
    description: 'Add values to php.ini.'
    required: false
  coverage: 
    description: 'Setup code coverage driver.'
    required: false
  tools:
    description: 'Setup popular tools globally.'
    required: false
  # Deprecated options, do not use. Will not be supported in v2 which will be released around February 1, 2020.
  extension-csv:
    description: 'Deprecated! Use extensions instead.'
    deprecationMessage: 'The extension-csv property will not be supported in v2. Use extensions instead.'
    required: false
  ini-values-csv:
    description: 'Deprecated! Use ini-values instead.'
    deprecationMessage: 'The ini-values-csv property will not be supported in v2. Use ini-values instead.'
    required: false
  pecl:
    description: 'Deprecated! Use tools instead to setup PECL.'
    deprecationMessage: 'The pecl property will not be supported in v2. Specify pecl in tools instead.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
