name: 'Setup PHP Action'
author: shivammathur
description: 'Setup a PHP environment with composer and add it to the PATH'
branding:
  icon: 'activity'  
  color: 'purple'
inputs:
  php-version:
    description: 'PHP version to install.'
runs:
  using: 'node12'
  main: 'lib/install.js'
