variants:
  dev:
    bcmath:
    calendar:
    cli:
    ctype:
    curl:
    dom:
    fileinfo:
    filter:
    gd:
      - --enable-exif
      - --enable-gd
      - --enable-intl
      - --enable-phpdbg
      - --enable-soap
      - --enable-sysvmsg
      - --enable-sysvsem
      - --enable-sysvshm
      - --enable-xml
      - --enable-xmlreader
      - --enable-zend-test=shared
      - --with-config-file-path=/etc
      - --with-curl
      - --with-ffi
      - --with-freetype
      - --with-gd
      - --with-gmp=/usr/local/opt/gmp
      - --with-iconv=/usr/local/opt/libiconv
      - --with-icu-dir=/usr/local/opt/icu4c
      - --with-kerberos
      - --with-libxml
      - --with-mhash
      - --with-mysqli=mysqlnd
      - --with-openssl
      - --with-pdo-mysql=mysqlnd
      - --with-pdo-pgsql
      - --with-pear
      - --with-pgsql
      - --with-readline=/usr/local/opt/readline
      - --with-zip
    iconv:
    ipc:
    json:
    mbregex:
    mbstring:
    mcrypt:
    mhash:
    openssl:
    pcntl:
    pcre:
    pdo:
    phar:
    posix:
    sockets:
    tokenizer:
    xml:
    zip:
